pdf_proj/customers/urls.py
from django.urls import path
from . views import render_pdf_view,CustomerListView,customer_render_pdf_view

app_name='customers'
urlpatterns=[
    path('',CustomerListView.as_view(),name='customer-list-view'),
    path('test',render_pdf_view,name='test-view'),
    path('pdf/<pk>/',customer_render_pdf_view,name='customer-pdf-view'),
]

pdf_proj/pdf_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customers.urls')),
]

pdf_proj/customers/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    name=models.CharField(max_length=200)
    logo=models.ImageField()
    description=models.TextField()
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.name)
    

pdf_proj/customers/views.py
from django.shortcuts import render,get_object_or_404

from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
#tambahan link
from django.views.generic import ListView
from .models import Customer
# Create your views here.

class CustomerListView(ListView):
   model = Customer
   template_name='main.html'



def customer_render_pdf_view(request,*args,**kwargs):
   pk=kwargs.get('pk')
   customer=get_object_or_404(Customer,pk=pk)
   # return HttpResponse("working")
   template_path = 'pdf2.html'
   context = {'customer': customer}
# Create a Django response object, and specify content_type as pdf
   response = HttpResponse(content_type='application/pdf')
    #if download:
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    #if display
   response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
   template = get_template(template_path)
   html = template.render(context)
    # create a pdf
   pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funny view
   if pisa_status.err:
      return HttpResponse('We had some errors <pre>' + html + '</pre>')
   return response



def render_pdf_view(request):
    template_path = 'pdf.html'
    context = {'myvar': 'this is your template context'}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    #if download:
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    #if display
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)
    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funny view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

pdf_proj/customers/templates/base/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{%block title%}{%endblock title%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      {% block content %}
      {% endblock content %}
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

pdf_proj/customers/templates/main.html
{% extends 'base/base.html' %}
{%block title%}
Customers
{%endblock title%}

{%block content%}
    
    {% for customer in object_list  %}
       {{customer}}
        <a href="{% url 'customers:customer-pdf-view' customer.pk %}"><button class="btn btn-primary">PDF</button></a>
        <br>
    {% endfor %}
        
{%endblock%}

pdf_proj/customers/templates/pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tampil PDF</title>
</head>
<body>
    {{myvar}}
</body>
</html>

pdf_proj/customers/templates/pdf2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tampil PDF</title>
</head>
<body>
    <img src="static/logo.jpg" alt="gambar tidak tersedia" height="200px">
    <h1>CAB.INC</h1>
    <p>opensource accounting software</p>
    <p>Nama Customer</p>{{customer}}
    <hr>
    {{customer.description|linebreaks}}
    <br>
    {{customer.logo}}
    <br>
    {{customer.logo.url}}
    <br>
    {{customer.logo.path}}
    

    <img src="{{customer.logo.path}}" alt="gambar tidak tersedia" height="200px">
    
</body>
</html>